<a href="https://colab.research.google.com/github/starkjones/Vienna-Air-BnB-Analysis/blob/main/Ecuador_Airbnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = '/content/drive/MyDrive/dataset_airbnb-scraper_2022-12-18_03-59-36-898_ML.xlsx'
df = pd.read_excel(data)
df.head(10)

,address,location/lat,location/lng,name,numberOfGuests,occupancy percentage,reviews/0/rating,reviews/1/rating,reviews/2/rating,reviews/3/rating,...,reviews/26/localizedReview/needsTranslation,reviews/26/localizedReview/response,reviews/26/rating,reviews/27/rating,reviews/28/rating,reviews/29/localizedReview/response,reviews/29/rating,roomType,stars,url
0,"Cuenca , Azuay, Ecuador",-2.88697,-78.95881,"3BR Duplex, Parking, Laundry, 24hr vídeo secur...",9,0.00,5.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Entire rental unit,NaN,https://www.airbnb.com/rooms/32477833
1,"Quito, Pichincha, Ecuador",-0.18413,-78.47900,Caravagio P2 Suite balcón lujo piscina rep sa...,2,2.38,5.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Entire rental unit,4.5,https://www.airbnb.com/rooms/53831514
2,"Cuenca, Azuay, Ecuador",-2.92100,-78.99900,Moderne Ecológica Suite - Amazing View - 104,2,5.95,5.0,5.0,4.0,4.0,...,NaN,NaN,5.0,5.0,5.0,NaN,5.0,Entire condo,5.0,https://www.airbnb.com/rooms/17809694
3,"Cuenca, Azuay, Ecuador",-2.88815,-79.00389,Amplia Habitación con Baño y Terraza privada,4,1.19,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private room in guesthouse,5.0,https://www.airbnb.com/rooms/49901522
4,"Baños de Agua Santa, Tungurahua, Ecuador",-1.38815,-78.41738,"Lovely Double Private Room, Baños, Ecuador, Ma...",3,9.52,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private room in bed and breakfast,5.0,https://www.airbnb.com/rooms/54035995
5,"Cuenca, Azuay, Ecuador",-2.90000,-79.02000,Beautiful and comfortable apartment,4,97.62,5.0,4.0,5.0,5.0,...,True,NaN,4.0,5.0,5.0,NaN,5.0,Entire rental unit,5.0,https://www.airbnb.com/rooms/26234857
6,"Loja, Ecuador",-4.00649,-79.19962,"Comfortable and safe, central. With parking.",8,0.00,5.0,4.0,5.0,5.0,...,True,NaN,4.0,5.0,5.0,NaN,2.0,Entire condo,4.5,https://www.airbnb.com/rooms/51691694
7,"Quito, Pichincha, Ecuador",-0.18035,-78.48102,Best place in Quito,2,21.43,5.0,5.0,5.0,5.0,...,NaN,NaN,5.0,5.0,5.0,NaN,5.0,Entire rental unit,5.0,https://www.airbnb.com/rooms/23357080
8,"Quito, Pichincha, Ecuador",-0.18930,-78.48296,Acogedor apartamento con vista al parque carolina,3,14.29,5.0,5.0,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Entire condo,4.5,https://www.airbnb.com/rooms/54209667
9,"Quito, Pichincha, Ecuador",-0.19468,-78.48185,Apartamento pequeño y acogedor muy bien ubicado.,5,34.52,4.0,5.0,5.0,5.0,...,True,NaN,5.0,3.0,5.0,NaN,5.0,Entire condo,4.5,https://www.airbnb.com/rooms/50216899

In [4]:
# check for duplciates:

df.duplicated().sum()

0

In [8]:
# check column datsatypes:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 64 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   address                                      280 non-null    object
 1   location/lat                                 280 non-null    float64
 2   location/lng                                 280 non-null    float64
 3   name                                         280 non-null    object
 4   numberOfGuests                               280 non-null    int64
 5   occupancy percentage                         280 non-null    float64
 6   reviews/0/rating                             248 non-null    float64
 7   reviews/1/rating                             234 non-null    float64
 8   reviews/2/rating                             223 non-null    float64
 9   reviews/3/rating                             219 non-null    float64
 10  reviews/4/rating                             215 non-null    float64
 11  reviews/5/rating                             211 non-null    float64
 12  reviews/6/rating                             207 non-null    float64
 13  reviews/7/rating                             206 non-null    float64
 14  reviews/8/rating                             200 non-null    float64
 15  reviews/9/rating                             198 non-null    float64
 16  reviews/10/rating                            193 non-null    float64
 17  reviews/11/rating                            184 non-null    float64
 18  reviews/12/rating                            182 non-null    float64
 19  reviews/13/rating                            179 non-null    float64
 20  reviews/14/rating                            173 non-null    float64
 21  reviews/15/rating                            170 non-null    float64
 22  reviews/16/rating                            166 non-null    float64
 23  reviews/17/rating                            159 non-null    float64
 24  reviews/18/rating                            155 non-null    float64
 25  reviews/19/rating                            149 non-null    float64
 26  reviews/20/rating                            147 non-null    float64
 27  reviews/21/rating                            145 non-null    float64
 28  reviews/22/rating                            140 non-null    float64
 29  reviews/23/rating                            138 non-null    float64
 30  reviews/24/rating                            137 non-null    float64
 31  reviews/25/rating                            135 non-null    float64
 32  reviews/25/recipient/firstName               135 non-null    object
 33  reviews/25/recipient/hasProfilePic           135 non-null    object
 34  reviews/25/recipient/id                      135 non-null    float64
 35  reviews/25/recipient/pictureUrl              135 non-null    object
 36  reviews/25/recipient/smartName               135 non-null    object
 37  reviews/25/recipient/thumbnailUrl            135 non-null    object
 38  reviews/25/response                          11 non-null     object
 39  reviews/26/author/firstName                  131 non-null    object
 40  reviews/26/author/hasProfilePic              131 non-null    object
 41  reviews/26/author/id                         131 non-null    float64
 42  reviews/26/author/pictureUrl                 131 non-null    object
 43  reviews/26/author/smartName                  131 non-null    object
 44  reviews/26/author/thumbnailUrl               131 non-null    object
 45  reviews/26/collectionTag                     0 non-null      float64
 46  reviews/26/comments                          130 non-null    object
 47  reviews/26/createdAt                         131 non-null    object
 48  reviews/26/id                                131 non-null    float64
 49  reviews/26/language                          79 non-null     object
 50  reviews/26/localizedDate                     131 non-null    object
 51  reviews/26/localizedReview                   0 non-null      float64
 52  reviews/26/localizedReview/comments          76 non-null     object
 53  reviews/26/localizedReview/disclaimer        79 non-null     object
 54  reviews/26/localizedReview/needsTranslation  79 non-null     object
 55  reviews/26/localizedReview/response          6 non-null      object
 56  reviews/26/rating                            131 non-null    float64
 57  reviews/27/rating                            128 non-null    float64
 58  reviews/28/rating                            124 non-null    float64
 59  reviews/29/localizedReview/response          5 non-null      object
 60  reviews/29/rating                            123 non-null    float64
 61  roomType                                     280 non-null    object
 62  stars                                        223 non-null    float64
 63  url                                          280 non-null    object
dtypes: float64(39), int64(1), object(24)
memory usage: 140.1+ KB

In [7]:
# check for missing values:

df.isna().sum()

address                                  0
location/lat                             0
location/lng                             0
name                                     0
numberOfGuests                           0
                                      ...
reviews/29/localizedReview/response    275
reviews/29/rating                      157
roomType                                 0
stars                                   57
url                                      0
Length: 64, dtype: int64